/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PLPSerialProgrammer.java
 *
 * Created on Jan 17, 2011, 9:35:18 AM
 */

package plptool.gui.frames;

import plptool.Config;
import plptool.Msg;
import plptool.Constants;
import plptool.PLPToolbox;
import plptool.gui.ProjectDriver;

import java.util.Enumeration;
import gnu.io.CommPortIdentifier;

/**
 *
 * @author wira
 */
public class ProgrammerDialog extends javax.swing.JDialog {

    ProjectDriver plp;

    public ProgrammerDialog(ProjectDriver plp, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.plp = plp;

        plptool.PLPToolbox.attachHideOnEscapeListener(this);

        cmbPort.removeAllItems();
        if(plp.isSerialSupported() && Config.prgAutoDetectPorts) {
            Enumeration portList = CommPortIdentifier.getPortIdentifiers();
            while (portList.hasMoreElements()) {
                CommPortIdentifier portId = (CommPortIdentifier) portList.nextElement();
                Msg.D("rxtx portId name: " + portId.getName() + " type: " + portId.getPortType(), 2 , null);
                if (portId.getPortType() == CommPortIdentifier.PORT_SERIAL) {
                    cmbPort.addItem(portId.getName());
                }
            }
        } else {
            if(PLPToolbox.getOS(false) == Constants.PLP_OS_LINUX_32 ||
               PLPToolbox.getOS(false) == Constants.PLP_OS_LINUX_64) {
                cmbPort.addItem("/dev/ttyUSB0");
                cmbPort.addItem("/dev/ttyUSB1");
                cmbPort.addItem("/dev/ttyS0");
                cmbPort.addItem("/dev/ttyS1");
            } else if(PLPToolbox.getOS(false) == Constants.PLP_OS_WIN_32 ||
               PLPToolbox.getOS(false) == Constants.PLP_OS_WIN_64) {
                cmbPort.addItem("COM1");
                cmbPort.addItem("COM2");
                cmbPort.addItem("COM3");
                cmbPort.addItem("COM4");
            } else
                cmbPort.addItem("Specify your serial port here.");
        }

        javax.swing.KeyStroke escapeKeyStroke = javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0, false);
        javax.swing.Action escapeAction = new javax.swing.AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
               setVisible(false);
               close();
            }
        };

        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
        
        this.setLocationRelativeTo(null);
    }

    public javax.swing.JProgressBar getProgressBar() {
        return progressBar;
    }

    public javax.swing.JTextField getStatusField() {
        return txtStatus;
    }

    public void program() {
        plp.program((String) cmbPort.getSelectedItem());
    }

    public void disableControls() {
        btnDownloadProgram.setEnabled(false);
        btnClose.setText("Cancel");
    }

    public void enableControls() {
        btnDownloadProgram.setEnabled(true);
        btnClose.setText("Close");
    }

    private void close() {
         if(plp.prg != null) {
            plp.prg.cancelProgramming();
            plp.prg.close();
        }
        progressBar.setValue(0);
        txtStatus.setText("");

        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPort = new javax.swing.JComboBox<String>();
        lblSerialPort = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        btnDownloadProgram = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(ProgrammerDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("Form"); // NOI18N
        setResizable(false);

        cmbPort.setEditable(true);
        cmbPort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPort.setName("cmbPort"); // NOI18N

        lblSerialPort.setText(resourceMap.getString("lblSerialPort.text")); // NOI18N
        lblSerialPort.setName("lblSerialPort"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        btnDownloadProgram.setText(resourceMap.getString("btnDownloadProgram.text")); // NOI18N
        btnDownloadProgram.setName("btnDownloadProgram"); // NOI18N
        btnDownloadProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadProgramActionPerformed(evt);
            }
        });

        btnClose.setText(resourceMap.getString("btnClose.text")); // NOI18N
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtStatus.setEditable(false);
        txtStatus.setText(resourceMap.getString("txtStatus.text")); // NOI18N
        txtStatus.setName("txtStatus"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSerialPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(cmbPort, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDownloadProgram)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDownloadProgram)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadProgramActionPerformed
        program();
    }//GEN-LAST:event_btnDownloadProgramActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDownloadProgram;
    private javax.swing.JComboBox<String> cmbPort;
    private javax.swing.JLabel lblSerialPort;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

}
