/*
    Copyright 2011 David Fritz, Brian Gordon, Wira Mulia

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

package plptool.mips.visualizer;

import plptool.mips.SimCore;
import plptool.Constants;
import javax.swing.JCheckBoxMenuItem;

/**
 *
 * @author wira
 */
public class CPUVisualization extends javax.swing.JFrame {

    private CPULevel1Canvas l1;
    private final SimCore sim;
    private JCheckBoxMenuItem menu;
    private int instructionsRetired;
    private int[] clrSelector = {0, 0, 0, 0, 0};

    public CPUVisualization(final SimCore sim, final JCheckBoxMenuItem menu) {
        initComponents();
        l1 = new CPULevel1Canvas(sim);
        l1.setSize(this.getSize());
        this.menu = menu;
        this.sim = sim;
        add(l1);
        instructionsRetired = 0;

        addWindowListener(new java.awt.event.WindowListener() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                setVisible(false);
                menu.setSelected(false);
                sim.bus.getRefMod(2).disable();
            }

            @Override public void windowOpened(java.awt.event.WindowEvent evt) { }
            @Override public void windowDeactivated(java.awt.event.WindowEvent evt) { }
            @Override public void windowActivated(java.awt.event.WindowEvent evt) { }
            @Override public void windowDeiconified(java.awt.event.WindowEvent evt) { }
            @Override public void windowIconified(java.awt.event.WindowEvent evt) { }
            @Override public void windowClosed(java.awt.event.WindowEvent evt) { }
        });
    }

    // called by SimCoreConnector's eval function
    public void update() {
        if(sim.wb_stage.instr_retired && !sim.wb_stage.bubble) {
            instructionsRetired++;
            l1.setInstructionsRetired(instructionsRetired);
        }

        l1.clearFwdFlags();


        clrSelector[0] = sim.id_stage.if_count % 5;
        clrSelector[1] = sim.id_stage.id_count % 5;
        clrSelector[2] = sim.ex_stage.count % 5;
        clrSelector[3] = sim.mem_stage.count % 5;
        clrSelector[4] = sim.wb_stage.count % 5;

        if(sim.getInstrCount() <= 0)
            reset();

        l1.setColorSelector(clrSelector);
        l1.repaint();
    }

    public void reset() {
        for(int i = 0; i < 5; i++)
            clrSelector[i] = 0;
        l1.setInstructionsRetired(0);
        instructionsRetired = 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(CPUVisualization.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
