/*
    Copyright 2011 David Fritz, Brian Gordon, Wira Mulia

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

package plptool.mips.visualizer;

import plptool.gui.ProjectDriver;
import plptool.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author wira
 */
public class MemoryVisualization extends javax.swing.JFrame {

    private ProjectDriver plp;
    private DrawPanel canvas;

    protected long startAddr = -1;
    protected long endAddr = -1;

    /** Creates new form MemoryVisualization */
    public MemoryVisualization(ProjectDriver plp) {
        initComponents();
        canvas = new DrawPanel(plp);
        canvas.setSize(container.getWidth(), container.getHeight());
        container.add(canvas);
        container.revalidate();

        this.plp = plp;
    }
    
    public void updateVisualization() {
        canvas.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStartAddr = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        txtEndAddr = new javax.swing.JTextField();
        btnVisualize = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(MemoryVisualization.class);
        txtStartAddr.setText(resourceMap.getString("txtStartAddr.text")); // NOI18N
        txtStartAddr.setName("txtStartAddr"); // NOI18N

        lbl1.setText(resourceMap.getString("lbl1.text")); // NOI18N
        lbl1.setName("lbl1"); // NOI18N

        txtEndAddr.setText(resourceMap.getString("txtEndAddr.text")); // NOI18N
        txtEndAddr.setName("txtEndAddr"); // NOI18N

        btnVisualize.setText(resourceMap.getString("btnVisualize.text")); // NOI18N
        btnVisualize.setName("btnVisualize"); // NOI18N
        btnVisualize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizeActionPerformed(evt);
            }
        });

        container.setName("container"); // NOI18N

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtStartAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisualize, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1)
                    .addComponent(txtEndAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizeActionPerformed
        try {
            startAddr = PLPToolbox.parseNum(txtStartAddr.getText());
            endAddr = PLPToolbox.parseNum(txtEndAddr.getText());
            updateVisualization();
        } catch(Exception e) {

        }
    }//GEN-LAST:event_btnVisualizeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualize;
    private javax.swing.JPanel container;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txtEndAddr;
    private javax.swing.JTextField txtStartAddr;
    // End of variables declaration//GEN-END:variables

    class DrawPanel extends JPanel {
        private ProjectDriver plp;

        public DrawPanel(ProjectDriver plp) {
            super();
            this.plp = plp;
        }

        @Override
        public void paint(Graphics g) {
            int W = this.getWidth();
            int H = this.getHeight();
            g.setColor(Color.white);
            g.fillRect(0, 0, W, H);
            long locs = (endAddr - startAddr) / 4;

            if(locs < 1)
                return;
            
            int rowH = H / (int) locs;

            Msg.D("locs: " + locs + " - rowH: " + rowH, 1, null);

            int i;
            
            for(i = 0; i < locs; i++) {
                g.setColor(Color.red);
                g.drawString(String.format("0x%08x", plp.sim.bus.read(startAddr + 4*i)), W / 2, 10 + i*rowH);
                g.setColor(Color.gray);
                g.drawString(String.format("0x%08x",startAddr + 4*i), 10, 10 + i*rowH);
                g.drawRect(10, i * rowH, W - 10, rowH);
            }
        }
    }
}


