
# version for gcc,  Sunworks cc, or others same except use different "CC="
# could add to CFLAGS to turn on warnings if you are using gcc
WARNS=-Wall

# change path if not running test from installed directory location
INCS=-I../../pli_incs
# maybe want -O<something> and/or -g, also maybe -march= option
CFLAGS= -Wall $(INCS)
LFLAGS= -G 

CC=gcc

dig_main.o:	dig_main.c 
	$(CC) $(CFLAGS) -c dig_main.c

vpiuser.o:	vpiuser.c 
	$(CC) $(CFLAGS) -c vpiuser.c

probe.o:	probe.c
	$(CC) $(CFLAGS) -c probe.c

tfclk.o:	tfclk.c
	$(CC) $(CFLAGS) -c tfclk.c

plimfil.o:	plimfil.c
	$(CC) $(CFLAGS) -c plimfil.c

plimfil2.o:	plimfil2.c
	$(CC) $(CFLAGS) -c plimfil2.c

# make rules for dynamic libaries
probe.so:	probe.o
	$(CC) $(LFLAGS) probe.o -o probe.so

tfclk.so:	tfclk.o 
	$(CC) $(LFLAGS) tfclk.o -o tfclk.so

plimfil.so:	plimfil.o 
	$(CC) $(LFLAGS) plimfil.o -o plimfil.so

plimfil2.so:	plimfil2.o 
	$(CC) $(LFLAGS) plimfil2.o -o plimfil2.so
