
# could add to CFLAGS to turn on warnings if you are using gcc
WARNS=-Wall

# change path if not running test from installed directory location
INCS=-I../../pli_incs
# maybe want -O<something> and/or -g, if you use -O use -march=
CFLAGS= -fPIC  -Wall $(INCS) -dynamic -fno-common 
LFLAGS= -flat_namespace -bundle -undefined suppress

# change to your compiler
# CC=gcc

probe.o:	probe.c 
	$(CC) $(CFLAGS) -c probe.c

tfclk.o:	tfclk.c 
	$(CC) $(CFLAGS) -c tfclk.c

plimfil.o:	plimfil.c
	$(CC) $(CFLAGS) -c plimfil.c

plimfil2.o:	plimfil2.c
	$(CC) $(CFLAGS) -c plimfil2.c

# make rules for dynamic libaries
probe.dylib:	probe.o
	$(CC) $(LFLAGS) probe.o -o probe.dylib

tfclk.dylib:	tfclk.o
	$(CC) $(LFLAGS) tfclk.o $(LFLAGS) -o tfclk.dylib

plimfil.dylib:	plimfil.o
	$(CC) $(LFLAGS) plimfil.o $(LFLAGS) -o plimfil.dylib

plimfil2.dylib:	plimfil2.o
	$(CC) $(LFLAGS) plimfil2.o $(LFLAGS) -o plimfil2.dylib
