/*
 * PLPToolView.java
 */

package plp;

import plptool.*;
import plpmips.*;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.awt.Color;

/**
 * The application's main frame.
 */
public class PLPToolView extends FrameView {

    static final int MAX_STEPS = 60000;

    public PLPToolView(SingleFrameApplication app) {
        super(app);

        initComponents();
        simFrame = null;
        PLPMsg.output = Output; // reroute PLPMsg output
        PLPMsg.M("PLPTool GUI\n");
        PLPMsg.m("Welcome to the GUI PLP software. You can start using this tool ");
        PLPMsg.M("by opening the Develop tab to write or open an assembly file.");
        PLPMainPane.setEnabledAt(1, false);
        PLPMainPane.setEnabledAt(2, false);
        
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = PLPToolApp.getApplication().getMainFrame();
            aboutBox = new PLPToolAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        PLPToolApp.getApplication().show(aboutBox);
    }

    public void plpMsgRouteBack() {
        PLPMsg.output = Output;
    }

    public void selectFirstPane(){
        PLPMainPane.setSelectedIndex(0);

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        PLPMainPane = new javax.swing.JTabbedPane();
        IDEPane = new javax.swing.JPanel();
        IDEBar = new javax.swing.JToolBar();
        IDENewBtn = new javax.swing.JButton();
        IDEOpenBtn = new javax.swing.JButton();
        IDESaveBtn = new javax.swing.JButton();
        IDESaveAsBtn = new javax.swing.JButton();
        IDEAssembleBtn = new javax.swing.JButton();
        IDEScroller = new javax.swing.JScrollPane();
        IDEStdOut = new javax.swing.JTextArea();
        IDESplitter = new javax.swing.JSplitPane();
        IDETreePane = new javax.swing.JScrollPane();
        IDEContextTree = new javax.swing.JTree();
        jScrollPane4 = new javax.swing.JScrollPane();
        IDEEditor = new javax.swing.JEditorPane();
        IDECommander = new javax.swing.JTextField();
        IDELabel_Command = new javax.swing.JLabel();
        SimPane = new javax.swing.JPanel();
        SimControls = new javax.swing.JPanel();
        btnStep = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtSteps = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        tglBusView = new javax.swing.JToggleButton();
        tglIODisplay = new javax.swing.JToggleButton();
        btnMem = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        SimDesktop = new javax.swing.JDesktopPane();
        PrgPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        OutputPane = new javax.swing.JPanel();
        OutputScrollPane = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plp.PLPToolApp.class).getContext().getResourceMap(PLPToolView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(plp.PLPToolApp.class).getContext().getActionMap(PLPToolView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        exitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMenuItemMouseReleased(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        PLPMainPane.setMinimumSize(new java.awt.Dimension(56, 55));
        PLPMainPane.setName("PLPMainPane"); // NOI18N

        IDEPane.setName("IDETab"); // NOI18N
        IDEPane.setVerifyInputWhenFocusTarget(false);

        IDEBar.setFloatable(false);
        IDEBar.setRollover(true);
        IDEBar.setName("IDEBar"); // NOI18N

        IDENewBtn.setText(resourceMap.getString("IDENewBtn.text")); // NOI18N
        IDENewBtn.setFocusable(false);
        IDENewBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IDENewBtn.setName("IDENewBtn"); // NOI18N
        IDENewBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IDEBar.add(IDENewBtn);

        IDEOpenBtn.setText(resourceMap.getString("IDEOpenBtn.text")); // NOI18N
        IDEOpenBtn.setFocusable(false);
        IDEOpenBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IDEOpenBtn.setName("IDEOpenBtn"); // NOI18N
        IDEOpenBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IDEBar.add(IDEOpenBtn);

        IDESaveBtn.setText(resourceMap.getString("IDESaveBtn.text")); // NOI18N
        IDESaveBtn.setFocusable(false);
        IDESaveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IDESaveBtn.setName("IDESaveBtn"); // NOI18N
        IDESaveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IDEBar.add(IDESaveBtn);

        IDESaveAsBtn.setText(resourceMap.getString("IDESaveAsBtn.text")); // NOI18N
        IDESaveAsBtn.setFocusable(false);
        IDESaveAsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IDESaveAsBtn.setName("IDESaveAsBtn"); // NOI18N
        IDESaveAsBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IDEBar.add(IDESaveAsBtn);

        IDEAssembleBtn.setText(resourceMap.getString("IDEAssembleBtn.text")); // NOI18N
        IDEAssembleBtn.setFocusable(false);
        IDEAssembleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IDEAssembleBtn.setName("IDEAssembleBtn"); // NOI18N
        IDEAssembleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IDEAssembleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDEAssembleBtnMouseClicked(evt);
            }
        });
        IDEAssembleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEAssembleBtnActionPerformed(evt);
            }
        });
        IDEBar.add(IDEAssembleBtn);

        IDEScroller.setName("IDEScroller"); // NOI18N

        IDEStdOut.setColumns(20);
        IDEStdOut.setEditable(false);
        IDEStdOut.setFont(resourceMap.getFont("IDEStdOut.font")); // NOI18N
        IDEStdOut.setRows(5);
        IDEStdOut.setName("IDEStdOut"); // NOI18N
        IDEScroller.setViewportView(IDEStdOut);

        IDESplitter.setResizeWeight(0.7);
        IDESplitter.setName("IDESplitter"); // NOI18N

        IDETreePane.setName("IDETreePane"); // NOI18N

        IDEContextTree.setName("IDEContextTree"); // NOI18N
        IDETreePane.setViewportView(IDEContextTree);

        IDESplitter.setRightComponent(IDETreePane);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        IDEEditor.setFont(resourceMap.getFont("IDEEditor.font")); // NOI18N
        IDEEditor.setName("IDEEditor"); // NOI18N
        jScrollPane4.setViewportView(IDEEditor);

        IDESplitter.setLeftComponent(jScrollPane4);

        IDECommander.setText(resourceMap.getString("IDECommander.text")); // NOI18N
        IDECommander.setName("IDECommander"); // NOI18N

        IDELabel_Command.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDELabel_Command.setText(resourceMap.getString("IDELabel_Command.text")); // NOI18N
        IDELabel_Command.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        IDELabel_Command.setInheritsPopupMenu(false);
        IDELabel_Command.setName("IDELabel_Command"); // NOI18N

        javax.swing.GroupLayout IDEPaneLayout = new javax.swing.GroupLayout(IDEPane);
        IDEPane.setLayout(IDEPaneLayout);
        IDEPaneLayout.setHorizontalGroup(
            IDEPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IDESplitter, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
            .addGroup(IDEPaneLayout.createSequentialGroup()
                .addComponent(IDELabel_Command)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDECommander, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
            .addComponent(IDEScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
            .addComponent(IDEBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );
        IDEPaneLayout.setVerticalGroup(
            IDEPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDEPaneLayout.createSequentialGroup()
                .addComponent(IDEBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDESplitter, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDEScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IDEPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDECommander, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDELabel_Command)))
        );

        PLPMainPane.addTab(resourceMap.getString("IDETab.TabConstraints.tabTitle"), IDEPane); // NOI18N

        SimPane.setEnabled(false);
        SimPane.setName("EmulatorTab"); // NOI18N

        SimControls.setName("SimControls"); // NOI18N

        btnStep.setText(resourceMap.getString("btnStep.text")); // NOI18N
        btnStep.setName("btnStep"); // NOI18N
        btnStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStepActionPerformed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jToggleButton1.setText(resourceMap.getString("jToggleButton1.text")); // NOI18N
        jToggleButton1.setName("jToggleButton1"); // NOI18N

        txtSteps.setText(resourceMap.getString("txtSteps.text")); // NOI18N
        txtSteps.setName("txtSteps"); // NOI18N

        btnReset.setText(resourceMap.getString("btnReset.text")); // NOI18N
        btnReset.setName("btnReset"); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tglBusView.setText(resourceMap.getString("tglBusView.text")); // NOI18N
        tglBusView.setName("tglBusView"); // NOI18N

        tglIODisplay.setText(resourceMap.getString("tglIODisplay.text")); // NOI18N
        tglIODisplay.setName("tglIODisplay"); // NOI18N

        btnMem.setText(resourceMap.getString("btnMem.text")); // NOI18N
        btnMem.setName("btnMem"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N

        javax.swing.GroupLayout SimControlsLayout = new javax.swing.GroupLayout(SimControls);
        SimControls.setLayout(SimControlsLayout);
        SimControlsLayout.setHorizontalGroup(
            SimControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addGap(18, 18, 18)
                .addComponent(tglBusView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglIODisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMem)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        SimControlsLayout.setVerticalGroup(
            SimControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimControlsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SimControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jToggleButton1)
                    .addComponent(btnStep)
                    .addComponent(txtSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset)
                    .addComponent(tglBusView)
                    .addComponent(tglIODisplay)
                    .addComponent(btnMem)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        SimDesktop.setBackground(resourceMap.getColor("SimDesktop.background")); // NOI18N
        SimDesktop.setAutoscrolls(true);
        SimDesktop.setName("SimDesktop"); // NOI18N

        javax.swing.GroupLayout SimPaneLayout = new javax.swing.GroupLayout(SimPane);
        SimPane.setLayout(SimPaneLayout);
        SimPaneLayout.setHorizontalGroup(
            SimPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SimControls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SimDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );
        SimPaneLayout.setVerticalGroup(
            SimPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SimPaneLayout.createSequentialGroup()
                .addComponent(SimDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SimControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PLPMainPane.addTab(resourceMap.getString("EmulatorTab.TabConstraints.tabTitle"), SimPane); // NOI18N

        PrgPane.setEnabled(false);
        PrgPane.setName("PrgPane"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setName("jComboBox2"); // NOI18N

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setName("jComboBox3"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout PrgPaneLayout = new javax.swing.GroupLayout(PrgPane);
        PrgPane.setLayout(PrgPaneLayout);
        PrgPaneLayout.setHorizontalGroup(
            PrgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrgPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 690, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 690, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, 690, Short.MAX_VALUE))
                .addContainerGap())
        );
        PrgPaneLayout.setVerticalGroup(
            PrgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrgPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PrgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PrgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(397, Short.MAX_VALUE))
        );

        PLPMainPane.addTab(resourceMap.getString("PrgPane.TabConstraints.tabTitle"), PrgPane); // NOI18N

        OutputPane.setName("OutputPane"); // NOI18N

        OutputScrollPane.setName("OutputScrollPane"); // NOI18N

        Output.setColumns(20);
        Output.setEditable(false);
        Output.setFont(resourceMap.getFont("Output.font")); // NOI18N
        Output.setRows(5);
        Output.setName("Output"); // NOI18N
        OutputScrollPane.setViewportView(Output);

        javax.swing.GroupLayout OutputPaneLayout = new javax.swing.GroupLayout(OutputPane);
        OutputPane.setLayout(OutputPaneLayout);
        OutputPaneLayout.setHorizontalGroup(
            OutputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutputPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OutputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                .addContainerGap())
        );
        OutputPaneLayout.setVerticalGroup(
            OutputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutputPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OutputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        PLPMainPane.addTab(resourceMap.getString("OutputPane.TabConstraints.tabTitle"), OutputPane); // NOI18N

        PLPMainPane.getAccessibleContext().setAccessibleName(resourceMap.getString("jTabbedPane1.AccessibleContext.accessibleName")); // NOI18N

        setComponent(PLPMainPane);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuItemMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItemMouseReleased

    private void IDEAssembleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDEAssembleBtnMouseClicked
        
    }//GEN-LAST:event_IDEAssembleBtnMouseClicked

    private void IDEAssembleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEAssembleBtnActionPerformed
        // TODO add your handling code here:
        int ret = 0;
        PLPMsg.output = IDEStdOut;
        PLPMsg.M("Assembling...");
        asm = new PLPAsm(IDEEditor.getText(), "IDEEditor", 0);

        if(simFrame != null) {
            simFrame.setVisible(false);
            simFrame.dispose();
        }

        if((ret = asm.preprocess(0)) == PLPMsg.PLP_OK) {
            ret = asm.assemble();
        }
        if(ret == PLPMsg.PLP_OK) {
            PLPMsg.M("Done.");
            PLPMainPane.setEnabledAt(1, true);
            PLPMainPane.setEnabledAt(2, true);
            sim = new PLPMIPSSim(asm, -1);
            sim.reset();
            sim.step();
            simFrame = new PLPMIPSCoreGUI(sim, this);
            SimDesktop.add(simFrame);
            PLPMsg.output = simFrame.getSimCLOutput();
            simFrame.setVisible(true);
            PLPMainPane.setSelectedIndex(1);
        }
        else {
            PLPMainPane.setEnabledAt(1, false);
            PLPMainPane.setEnabledAt(2, false);
            
            PLPMsg.M("Fix your code.");
            PLPMsg.M("");
            PLPMsg.output = Output;
        }
    }//GEN-LAST:event_IDEAssembleBtnActionPerformed

    private void btnStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStepActionPerformed
        // TODO add your handling code here:
        try {
            int steps = Integer.parseInt(txtSteps.getText());
            if(steps <= MAX_STEPS && steps > 0) {
                for(int i = 0; i < steps; i++)
                    sim.step();
                simFrame.updateComponents();
            } else {
                txtSteps.setText("1");
            }
        } catch(Exception e) {
            txtSteps.setText("1");
        }
    }//GEN-LAST:event_btnStepActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        sim.reset();
        simFrame.updateComponents();
    }//GEN-LAST:event_btnResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDEAssembleBtn;
    private javax.swing.JToolBar IDEBar;
    private javax.swing.JTextField IDECommander;
    private javax.swing.JTree IDEContextTree;
    private javax.swing.JEditorPane IDEEditor;
    private javax.swing.JLabel IDELabel_Command;
    private javax.swing.JButton IDENewBtn;
    private javax.swing.JButton IDEOpenBtn;
    private javax.swing.JPanel IDEPane;
    private javax.swing.JButton IDESaveAsBtn;
    private javax.swing.JButton IDESaveBtn;
    private javax.swing.JScrollPane IDEScroller;
    private javax.swing.JSplitPane IDESplitter;
    private javax.swing.JTextArea IDEStdOut;
    private javax.swing.JScrollPane IDETreePane;
    private javax.swing.JTextArea Output;
    private javax.swing.JPanel OutputPane;
    private javax.swing.JScrollPane OutputScrollPane;
    private javax.swing.JTabbedPane PLPMainPane;
    private javax.swing.JPanel PrgPane;
    private javax.swing.JPanel SimControls;
    private javax.swing.JDesktopPane SimDesktop;
    private javax.swing.JPanel SimPane;
    private javax.swing.JToggleButton btnMem;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStep;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JToggleButton tglBusView;
    private javax.swing.JToggleButton tglIODisplay;
    private javax.swing.JTextField txtSteps;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;
    private plpmips.PLPMIPSCoreGUI simFrame;

    // Backends
    public PLPMIPSSim sim;
    public PLPAsm asm;
    public PLPProgrammer prg;

}
