/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ASMExplorer.java
 *
 * Created on Mar 28, 2011, 7:48:30 PM
 */

package plptool.gui;

import plptool.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/**
 *
 * @author wira
 */
public class ASMExplorer extends javax.swing.JFrame {

    private ProjectDriver plp;

    /** Creates new form ASMExplorer */
    public ASMExplorer(ProjectDriver plp) {
        initComponents();

        this.plp = plp;
        updateTable();
    }

    public final void updateTable() {
        DefaultTableModel model = (DefaultTableModel) tblASM.getModel();

        while(model.getRowCount() > 0)
            model.removeRow(0);

        long[] objCode = plp.asm.getObjectCode();

        for(int i = 0; i < objCode.length; i++) {
            Object[] row = new Object[] {
                String.format("0x%08x", plp.asm.getAddrTable()[i]) +
                        " " + ((plp.sim != null) ?
                            ((((plptool.mips.SimCore) plp.sim).pc.eval() == plp.asm.getAddrTable()[i]) ? "[PC]" : "")
                            : ""),
                String.format("0x%08x", objCode[i]),
                plp.asm.getAsmList().get(plp.asm.getFileMapper()[i]).getAsmFilePath(),
                plp.asm.getLineNumMapper()[i],
                plp.asm.getAsmList().get(plp.asm.getFileMapper()[i]).getAsmLine(plp.asm.getLineNumMapper()[i])
            };

            model.addRow(row);
        }

        tblASM.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlTblASM = new javax.swing.JScrollPane();
        tblASM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        scrlTblASM.setName("scrlTblASM"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(ASMExplorer.class);
        tblASM.setFont(resourceMap.getFont("tblASM.font")); // NOI18N
        tblASM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Addr", "Instr", "File", "Line #", "LineStr"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblASM.setName("tblASM"); // NOI18N
        scrlTblASM.setViewportView(tblASM);
        tblASM.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblASM.columnModel.title0")); // NOI18N
        tblASM.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblASM.columnModel.title1")); // NOI18N
        tblASM.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblASM.columnModel.title3")); // NOI18N
        tblASM.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblASM.columnModel.title4")); // NOI18N
        tblASM.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tblASM.columnModel.title2")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlTblASM, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlTblASM, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrlTblASM;
    private javax.swing.JTable tblASM;
    // End of variables declaration//GEN-END:variables

}
