/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PLPMIPSCoreGUI.java
 *
 * Created on Dec 4, 2010, 12:12:09 AM
 */

package plpmips;

import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author wira
 */
public class PLPMIPSCoreGUI extends javax.swing.JInternalFrame {

    private PLPMIPSSim sim;
    private plp.PLPToolView mainWindow;

    /** Creates new form PLPMIPSCoreGUI */
    public PLPMIPSCoreGUI(PLPMIPSSim sim, plp.PLPToolView mainWindow) {
        this.sim = sim;
        this.mainWindow = mainWindow;
        initComponents();
        renderer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tblRegFile.setDefaultRenderer(tblRegFile.getColumnClass(2), renderer);

        tblRegFile.setValueAt("0: $zero", 0, 0);
        tblRegFile.setValueAt("1: $at", 1, 0);
        tblRegFile.setValueAt("2: $v0", 2, 0);
        tblRegFile.setValueAt("3: $v1", 3, 0);
        tblRegFile.setValueAt("4: $a0", 4, 0);
        tblRegFile.setValueAt("5: $a1", 5, 0);
        tblRegFile.setValueAt("6: $a2", 6, 0);
        tblRegFile.setValueAt("7: $a3", 7, 0);
        tblRegFile.setValueAt("8: $t0", 8, 0);
        tblRegFile.setValueAt("9: $t1", 9, 0);
        tblRegFile.setValueAt("10: $t2", 10, 0);
        tblRegFile.setValueAt("11: $t3", 11, 0);
        tblRegFile.setValueAt("12: $t4", 12, 0);
        tblRegFile.setValueAt("13: $t5", 13, 0);
        tblRegFile.setValueAt("14: $t6", 14, 0);
        tblRegFile.setValueAt("15: $t7", 15, 0);
        tblRegFile.setValueAt("16: $s0", 16, 0);
        tblRegFile.setValueAt("17: $s1", 17, 0);
        tblRegFile.setValueAt("18: $s2", 18, 0);
        tblRegFile.setValueAt("19: $s3", 19, 0);
        tblRegFile.setValueAt("20: $s4", 20, 0);
        tblRegFile.setValueAt("21: $s5", 21, 0);
        tblRegFile.setValueAt("22: $s6", 22, 0);
        tblRegFile.setValueAt("23: $s7", 23, 0);
        tblRegFile.setValueAt("24: $t8", 24, 0);
        tblRegFile.setValueAt("25: $t9", 25, 0);
        tblRegFile.setValueAt("26: $k0", 26, 0);
        tblRegFile.setValueAt("27: $k1", 27, 0);
        tblRegFile.setValueAt("28: $gp", 28, 0);
        tblRegFile.setValueAt("29: $sp", 29, 0);
        tblRegFile.setValueAt("30: $fp", 30, 0);
        tblRegFile.setValueAt("31: $ra", 31, 0);

        updateComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nextInstr = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegFile = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProgram = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMemMap = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        simCLOutput = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        simCLConsole = new javax.swing.JTextField();
        simCLExec = new javax.swing.JButton();
        simCLClear = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plp.PLPToolApp.class).getContext().getResourceMap(PLPMIPSCoreGUI.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        PC.setEditable(false);
        PC.setText(resourceMap.getString("PC.text")); // NOI18N
        PC.setName("PC"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        nextInstr.setEditable(false);
        nextInstr.setText(resourceMap.getString("nextInstr.text")); // NOI18N
        nextInstr.setName("nextInstr"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblRegFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Register", "Contents", "Edit Contents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegFile.setColumnSelectionAllowed(true);
        tblRegFile.setName("tblRegFile"); // NOI18N
        tblRegFile.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblRegFile);
        tblRegFile.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblRegFile.getColumnModel().getColumn(0).setResizable(false);
        tblRegFile.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblRegFile.columnModel.title0")); // NOI18N
        tblRegFile.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblRegFile.columnModel.title1")); // NOI18N
        tblRegFile.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblRegFile.columnModel.title2")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        tblProgram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "PC", "Breakpoint", "Address", "Instruction (Hex)", "Instruction"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProgram.setName("tblProgram"); // NOI18N
        tblProgram.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblProgram);
        tblProgram.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblProgram.columnModel.title0")); // NOI18N
        tblProgram.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblProgram.columnModel.title1")); // NOI18N
        tblProgram.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblProgram.columnModel.title2")); // NOI18N
        tblProgram.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblProgram.columnModel.title3")); // NOI18N
        tblProgram.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tblProgram.columnModel.title4")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblMemMap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Index", "Module Name", "Start Address", "End Address", "Enabled"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMemMap.setName("tblMemMap"); // NOI18N
        tblMemMap.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblMemMap);
        tblMemMap.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblMemMap.columnModel.title0")); // NOI18N
        tblMemMap.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblMemMap.columnModel.title1")); // NOI18N
        tblMemMap.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblMemMap.columnModel.title2")); // NOI18N
        tblMemMap.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblMemMap.columnModel.title3")); // NOI18N
        tblMemMap.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tblMemMap.columnModel.title4")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jCheckBox2.setText(resourceMap.getString("jCheckBox2.text")); // NOI18N
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N

        jRadioButton3.setText(resourceMap.getString("jRadioButton3.text")); // NOI18N
        jRadioButton3.setName("jRadioButton3"); // NOI18N

        jRadioButton4.setText(resourceMap.getString("jRadioButton4.text")); // NOI18N
        jRadioButton4.setName("jRadioButton4"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel6.TabConstraints.tabTitle"), jPanel6); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane4.setEnabled(false);
        jScrollPane4.setName("jScrollPane4"); // NOI18N

        simCLOutput.setColumns(20);
        simCLOutput.setEditable(false);
        simCLOutput.setFont(resourceMap.getFont("simCLOutput.font")); // NOI18N
        simCLOutput.setLineWrap(true);
        simCLOutput.setRows(5);
        simCLOutput.setWrapStyleWord(true);
        simCLOutput.setMinimumSize(new java.awt.Dimension(0, 0));
        simCLOutput.setName("simCLOutput"); // NOI18N
        jScrollPane4.setViewportView(simCLOutput);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        simCLConsole.setText(resourceMap.getString("simCLConsole.text")); // NOI18N
        simCLConsole.setName("simCLConsole"); // NOI18N
        simCLConsole.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                simCLConsoleKeyPressed(evt);
            }
        });

        simCLExec.setText(resourceMap.getString("simCLExec.text")); // NOI18N
        simCLExec.setName("simCLExec"); // NOI18N
        simCLExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simCLExecActionPerformed(evt);
            }
        });

        simCLClear.setText(resourceMap.getString("simCLClear.text")); // NOI18N
        simCLClear.setName("simCLClear"); // NOI18N
        simCLClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simCLClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(simCLConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simCLExec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simCLClear))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simCLClear)
                    .addComponent(simCLExec)
                    .addComponent(simCLConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextInstr, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nextInstr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simCLClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simCLClearActionPerformed
        // TODO add your handling code here:
        simCLOutput.setText("");
}//GEN-LAST:event_simCLClearActionPerformed

    private void simCLExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simCLExecActionPerformed
        // TODO add your handling code here:
        plptool.PLPMsg.output = simCLOutput;
        plpmips.PLPSimCL.init_core = true;
        simCLOutput.append(simCLConsole.getText() + "\n");
        plpmips.PLPSimCL.simCLCommand(simCLConsole.getText(), sim);
        simCLConsole.setText("");
        updateComponents();
}//GEN-LAST:event_simCLExecActionPerformed

    private void simCLConsoleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_simCLConsoleKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            simCLExecActionPerformed(null);
}//GEN-LAST:event_simCLConsoleKeyPressed

    public void updateComponents() {
        long pc = sim.pc.eval();
        if(pc >= 0) {
            PC.setText(String.format("0x%08x", pc));
            nextInstr.setText(MIPSInstr.format(sim.id_stage.i_instruction));
        } else {
            PC.setText(String.format("0xXXXXXXXX"));
            nextInstr.setText("Unknown");
        }

        for(int i = 0; i < 32; i++) {
            tblRegFile.setValueAt(sim.regfile.read(i), i, 2);
            tblRegFile.setValueAt(String.format("0x%08x", sim.regfile.read(i)), i, 1);
        }
    }

    public javax.swing.JTextArea getSimCLOutput() {
        return simCLOutput;
    }

    public javax.swing.JTextField getSimCLConsole() {
        return simCLConsole;
    }

    private javax.swing.table.DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PC;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nextInstr;
    private javax.swing.JButton simCLClear;
    private javax.swing.JTextField simCLConsole;
    private javax.swing.JButton simCLExec;
    private javax.swing.JTextArea simCLOutput;
    private javax.swing.JTable tblMemMap;
    private javax.swing.JTable tblProgram;
    private javax.swing.JTable tblRegFile;
    // End of variables declaration//GEN-END:variables

}
