/*
    Copyright 2010 David Fritz, Brian Gordon, Wira Mulia

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

/*
 * LEDArrayFrame.java
 *
 * Created on Dec 6, 2010, 7:06:23 PM
 */

package plptool.mods;

/**
 *
 * @author wira
 */
public class LEDArrayFrame extends javax.swing.JFrame {

    /** Creates new form LEDArrayFrame */
    public LEDArrayFrame() {
        this.setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("resources/toolbar_sim_leds.png")));
        initComponents();
    }

    public void setAddress(long addr) {
        txtAddress.setText(String.format("0x%08x", addr));
    }

    public void setValue(long value) {
        txtValue.setText(String.format("0x%08x", value));
    }

    public javax.swing.JLabel getLED(int index) {
        switch(index) {
            case 0:
                return bit0;
            case 1:
                return bit1;
            case 2:
                return bit2;
            case 3:
                return bit3;
            case 4:
                return bit4;
            case 5:
                return bit5;
            case 6:
                return bit6;
            case 7:
                return bit7;
            default:
                return null;
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        bit1 = new javax.swing.JLabel();
        bit0 = new javax.swing.JLabel();
        bit3 = new javax.swing.JLabel();
        bit2 = new javax.swing.JLabel();
        bit7 = new javax.swing.JLabel();
        bit6 = new javax.swing.JLabel();
        bit5 = new javax.swing.JLabel();
        bit4 = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(LEDArrayFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        lblAddress.setText(resourceMap.getString("lblAddress.text")); // NOI18N
        lblAddress.setName("lblAddress"); // NOI18N

        txtAddress.setEditable(false);
        txtAddress.setText(resourceMap.getString("txtAddress.text")); // NOI18N
        txtAddress.setName("txtAddress"); // NOI18N

        bit1.setBackground(resourceMap.getColor("bit4.background")); // NOI18N
        bit1.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        bit1.setForeground(resourceMap.getColor("bit1.foreground")); // NOI18N
        bit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit1.setText(resourceMap.getString("bit1.text")); // NOI18N
        bit1.setName("bit1"); // NOI18N
        bit1.setOpaque(true);

        bit0.setBackground(resourceMap.getColor("bit4.background")); // NOI18N
        bit0.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        bit0.setForeground(resourceMap.getColor("bit0.foreground")); // NOI18N
        bit0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit0.setText(resourceMap.getString("bit0.text")); // NOI18N
        bit0.setName("bit0"); // NOI18N
        bit0.setOpaque(true);

        bit3.setBackground(resourceMap.getColor("bit4.background")); // NOI18N
        bit3.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        bit3.setForeground(resourceMap.getColor("bit3.foreground")); // NOI18N
        bit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit3.setText(resourceMap.getString("bit3.text")); // NOI18N
        bit3.setName("bit3"); // NOI18N
        bit3.setOpaque(true);

        bit2.setBackground(resourceMap.getColor("bit4.background")); // NOI18N
        bit2.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        bit2.setForeground(resourceMap.getColor("bit2.foreground")); // NOI18N
        bit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit2.setText(resourceMap.getString("bit2.text")); // NOI18N
        bit2.setName("bit2"); // NOI18N
        bit2.setOpaque(true);

        bit7.setBackground(resourceMap.getColor("bit4.background")); // NOI18N
        bit7.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        bit7.setForeground(resourceMap.getColor("bit7.foreground")); // NOI18N
        bit7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit7.setText(resourceMap.getString("bit7.text")); // NOI18N
        bit7.setName("bit7"); // NOI18N
        bit7.setOpaque(true);

        bit6.setBackground(resourceMap.getColor("bit4.background")); // NOI18N
        bit6.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        bit6.setForeground(resourceMap.getColor("bit6.foreground")); // NOI18N
        bit6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit6.setText(resourceMap.getString("bit6.text")); // NOI18N
        bit6.setName("bit6"); // NOI18N
        bit6.setOpaque(true);

        bit5.setBackground(resourceMap.getColor("bit4.background")); // NOI18N
        bit5.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        bit5.setForeground(resourceMap.getColor("bit5.foreground")); // NOI18N
        bit5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit5.setText(resourceMap.getString("bit5.text")); // NOI18N
        bit5.setName("bit5"); // NOI18N
        bit5.setOpaque(true);

        bit4.setBackground(resourceMap.getColor("bit4.background")); // NOI18N
        bit4.setFont(resourceMap.getFont("bit4.font")); // NOI18N
        bit4.setForeground(resourceMap.getColor("bit4.foreground")); // NOI18N
        bit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bit4.setText(resourceMap.getString("bit4.text")); // NOI18N
        bit4.setName("bit4"); // NOI18N
        bit4.setOpaque(true);

        lblValue.setText(resourceMap.getString("lblValue.text")); // NOI18N
        lblValue.setName("lblValue"); // NOI18N

        txtValue.setEditable(false);
        txtValue.setText(resourceMap.getString("txtValue.text")); // NOI18N
        txtValue.setName("txtValue"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bit7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bit6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bit5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bit4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bit3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bit2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bit1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bit0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValue, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValue)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bit6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bit0;
    private javax.swing.JLabel bit1;
    private javax.swing.JLabel bit2;
    private javax.swing.JLabel bit3;
    private javax.swing.JLabel bit4;
    private javax.swing.JLabel bit5;
    private javax.swing.JLabel bit6;
    private javax.swing.JLabel bit7;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables

}
