/*
    Copyright 2010 David Fritz, Brian Gordon, Wira Mulia

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

/*
 * SevenSegmentsFrame.java
 *
 * Created on Mar 2, 2011, 8:40:48 PM
 */

package plptool.mods;

/**
 *
 * @author wira
 */
public class SevenSegmentsFrame extends javax.swing.JFrame {

    /** Creates new form SevenSegmentsFrame */
    public SevenSegmentsFrame() {
        this.setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("resources/toolbar_sim_7segments.png")));
        initComponents();
    }

    public void setAddress(long addr) {
        txtAddress.setText(String.format("0x%08x", addr));
    }

    public void setValue(long value) {
        txtValue.setText(String.format("0x%08x", value));
    }

    public javax.swing.JLabel getLED(int hIndex, int bit) {
        switch(hIndex) {
            case 0:
                switch(bit) {
                    case 0: return h0b0;
                    case 1: return h0b1;
                    case 2: return h0b2;
                    case 3: return h0b3;
                    case 4: return h0b4;
                    case 5: return h0b5;
                    case 6: return h0b6;
                    case 7: return h0b7;
                    default: return null;
                }
            case 1:
                switch(bit) {
                    case 0: return h1b0;
                    case 1: return h1b1;
                    case 2: return h1b2;
                    case 3: return h1b3;
                    case 4: return h1b4;
                    case 5: return h1b5;
                    case 6: return h1b6;
                    case 7: return h1b7;
                    default: return null;
                }
            case 2:
                switch(bit) {
                    case 0: return h2b0;
                    case 1: return h2b1;
                    case 2: return h2b2;
                    case 3: return h2b3;
                    case 4: return h2b4;
                    case 5: return h2b5;
                    case 6: return h2b6;
                    case 7: return h2b7;
                    default: return null;
                }
            case 3:
                switch(bit) {
                    case 0: return h3b0;
                    case 1: return h3b1;
                    case 2: return h3b2;
                    case 3: return h3b3;
                    case 4: return h3b4;
                    case 5: return h3b5;
                    case 6: return h3b6;
                    case 7: return h3b7;
                    default: return null;
                }
            default:
                return null;
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        h3b1 = new javax.swing.JLabel();
        h3b6 = new javax.swing.JLabel();
        h3b0 = new javax.swing.JLabel();
        h3b5 = new javax.swing.JLabel();
        h3b2 = new javax.swing.JLabel();
        h2b7 = new javax.swing.JLabel();
        h3b4 = new javax.swing.JLabel();
        h3b3 = new javax.swing.JLabel();
        h2b6 = new javax.swing.JLabel();
        h2b4 = new javax.swing.JLabel();
        h2b3 = new javax.swing.JLabel();
        h2b2 = new javax.swing.JLabel();
        h2b1 = new javax.swing.JLabel();
        h2b0 = new javax.swing.JLabel();
        h2b5 = new javax.swing.JLabel();
        h1b1 = new javax.swing.JLabel();
        h1b6 = new javax.swing.JLabel();
        h1b0 = new javax.swing.JLabel();
        h1b5 = new javax.swing.JLabel();
        h1b2 = new javax.swing.JLabel();
        h1b3 = new javax.swing.JLabel();
        h1b4 = new javax.swing.JLabel();
        h0b6 = new javax.swing.JLabel();
        h0b4 = new javax.swing.JLabel();
        h0b3 = new javax.swing.JLabel();
        h0b2 = new javax.swing.JLabel();
        h0b1 = new javax.swing.JLabel();
        h0b0 = new javax.swing.JLabel();
        h0b5 = new javax.swing.JLabel();
        h3b7 = new javax.swing.JLabel();
        h0b7 = new javax.swing.JLabel();
        h1b7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(SevenSegmentsFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        lblAddress.setText(resourceMap.getString("lblAddress.text")); // NOI18N
        lblAddress.setName("lblAddress"); // NOI18N

        txtAddress.setEditable(false);
        txtAddress.setName("txtAddress"); // NOI18N

        lblValue.setText(resourceMap.getString("lblValue.text")); // NOI18N
        lblValue.setName("lblValue"); // NOI18N

        txtValue.setEditable(false);
        txtValue.setName("txtValue"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        h3b1.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h3b1.setText(resourceMap.getString("h3b1.text")); // NOI18N
        h3b1.setName("h3b1"); // NOI18N
        h3b1.setOpaque(true);
        jPanel1.add(h3b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 10, 30));

        h3b6.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h3b6.setName("h3b6"); // NOI18N
        h3b6.setOpaque(true);
        jPanel1.add(h3b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 40, 10));

        h3b0.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h3b0.setName("h3b0"); // NOI18N
        h3b0.setOpaque(true);
        jPanel1.add(h3b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 10));

        h3b5.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h3b5.setName("h3b5"); // NOI18N
        h3b5.setOpaque(true);
        jPanel1.add(h3b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 10, 30));

        h3b2.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h3b2.setName("h3b2"); // NOI18N
        h3b2.setOpaque(true);
        jPanel1.add(h3b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 10, 30));

        h2b7.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h2b7.setName("h2b7"); // NOI18N
        h2b7.setOpaque(true);
        jPanel1.add(h2b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 10, 10));

        h3b4.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h3b4.setName("h3b4"); // NOI18N
        h3b4.setOpaque(true);
        jPanel1.add(h3b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 10, 30));

        h3b3.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h3b3.setName("h3b3"); // NOI18N
        h3b3.setOpaque(true);
        jPanel1.add(h3b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 10));

        h2b6.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h2b6.setName("h2b6"); // NOI18N
        h2b6.setOpaque(true);
        jPanel1.add(h2b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 40, 10));

        h2b4.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h2b4.setName("h2b4"); // NOI18N
        h2b4.setOpaque(true);
        jPanel1.add(h2b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 10, 30));

        h2b3.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h2b3.setName("h2b3"); // NOI18N
        h2b3.setOpaque(true);
        jPanel1.add(h2b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 40, 10));

        h2b2.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h2b2.setName("h2b2"); // NOI18N
        h2b2.setOpaque(true);
        jPanel1.add(h2b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 10, 30));

        h2b1.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h2b1.setName("h2b1"); // NOI18N
        h2b1.setOpaque(true);
        jPanel1.add(h2b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 10, 30));

        h2b0.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h2b0.setName("h2b0"); // NOI18N
        h2b0.setOpaque(true);
        jPanel1.add(h2b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 40, 10));

        h2b5.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h2b5.setName("h2b5"); // NOI18N
        h2b5.setOpaque(true);
        jPanel1.add(h2b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 10, 30));

        h1b1.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h1b1.setName("h1b1"); // NOI18N
        h1b1.setOpaque(true);
        jPanel1.add(h1b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 10, 30));

        h1b6.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h1b6.setName("h1b6"); // NOI18N
        h1b6.setOpaque(true);
        jPanel1.add(h1b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 40, 10));

        h1b0.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h1b0.setName("h1b0"); // NOI18N
        h1b0.setOpaque(true);
        jPanel1.add(h1b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 40, 10));

        h1b5.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h1b5.setName("h1b5"); // NOI18N
        h1b5.setOpaque(true);
        jPanel1.add(h1b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 10, 30));

        h1b2.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h1b2.setName("h1b2"); // NOI18N
        h1b2.setOpaque(true);
        jPanel1.add(h1b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 10, 30));

        h1b3.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h1b3.setName("h1b3"); // NOI18N
        h1b3.setOpaque(true);
        jPanel1.add(h1b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 40, 10));

        h1b4.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h1b4.setName("h1b4"); // NOI18N
        h1b4.setOpaque(true);
        jPanel1.add(h1b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 10, 30));

        h0b6.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h0b6.setName("h0b6"); // NOI18N
        h0b6.setOpaque(true);
        jPanel1.add(h0b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 40, 10));

        h0b4.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h0b4.setName("h0b4"); // NOI18N
        h0b4.setOpaque(true);
        jPanel1.add(h0b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 10, 30));

        h0b3.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h0b3.setName("h0b3"); // NOI18N
        h0b3.setOpaque(true);
        jPanel1.add(h0b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 40, 10));

        h0b2.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h0b2.setName("h0b2"); // NOI18N
        h0b2.setOpaque(true);
        jPanel1.add(h0b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 10, 30));

        h0b1.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h0b1.setName("h0b1"); // NOI18N
        h0b1.setOpaque(true);
        jPanel1.add(h0b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 10, 30));

        h0b0.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h0b0.setName("h0b0"); // NOI18N
        h0b0.setOpaque(true);
        jPanel1.add(h0b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 10));

        h0b5.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h0b5.setName("h0b5"); // NOI18N
        h0b5.setOpaque(true);
        jPanel1.add(h0b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 10, 30));

        h3b7.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h3b7.setName("h3b7"); // NOI18N
        h3b7.setOpaque(true);
        jPanel1.add(h3b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 10, 10));

        h0b7.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h0b7.setName("h0b7"); // NOI18N
        h0b7.setOpaque(true);
        jPanel1.add(h0b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 10, 10));

        h1b7.setBackground(resourceMap.getColor("h0b6.background")); // NOI18N
        h1b7.setName("h1b7"); // NOI18N
        h1b7.setOpaque(true);
        jPanel1.add(h1b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addGap(16, 16, 16)
                        .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(lblValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress)
                    .addComponent(lblValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel h0b0;
    private javax.swing.JLabel h0b1;
    private javax.swing.JLabel h0b2;
    private javax.swing.JLabel h0b3;
    private javax.swing.JLabel h0b4;
    private javax.swing.JLabel h0b5;
    private javax.swing.JLabel h0b6;
    private javax.swing.JLabel h0b7;
    private javax.swing.JLabel h1b0;
    private javax.swing.JLabel h1b1;
    private javax.swing.JLabel h1b2;
    private javax.swing.JLabel h1b3;
    private javax.swing.JLabel h1b4;
    private javax.swing.JLabel h1b5;
    private javax.swing.JLabel h1b6;
    private javax.swing.JLabel h1b7;
    private javax.swing.JLabel h2b0;
    private javax.swing.JLabel h2b1;
    private javax.swing.JLabel h2b2;
    private javax.swing.JLabel h2b3;
    private javax.swing.JLabel h2b4;
    private javax.swing.JLabel h2b5;
    private javax.swing.JLabel h2b6;
    private javax.swing.JLabel h2b7;
    private javax.swing.JLabel h3b0;
    private javax.swing.JLabel h3b1;
    private javax.swing.JLabel h3b2;
    private javax.swing.JLabel h3b3;
    private javax.swing.JLabel h3b4;
    private javax.swing.JLabel h3b5;
    private javax.swing.JLabel h3b6;
    private javax.swing.JLabel h3b7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables

}
