/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SampleFrame.java
 *
 * Created on Oct 31, 2011, 10:33:32 PM
 */

package plptimingdiagram.draw;

import plptimingdiagram.*;
import plptimingdiagram.signals.*;

/**
 *
 * @author wira
 */
public class SampleFrame extends javax.swing.JFrame {

    private DiagramCanvas canvas;
    private TimingDiagram tD;
    private XAxis axis;

    /** Creates new form SampleFrame */
    public SampleFrame() {
        initComponents();
        tD = new TimingDiagram();
        axis = new XAxis(0, 100, 10);
        canvas = new DiagramCanvas(tD, axis);
        canvas.setSize(container.getWidth(), container.getHeight());
        container.add(canvas);
        container.revalidate();

        tD.addSignal(new Line());
        tD.addSignal(new Line());
        tD.addSignal(new Line());


        tD.getSignal(0).setName("Signal Number One");
        tD.getSignal(0).addEdge(new LineEdge(0, false));
        tD.getSignal(0).addEdge(new LineEdge(10, true));
        tD.getSignal(0).addEdge(new LineEdge(20, false));
        tD.getSignal(0).addEdge(new LineEdge(30, true));
        tD.getSignal(0).addEdge(new LineEdge(40, false));
        tD.getSignal(0).addEdge(new LineEdge(50, true));
        tD.getSignal(0).addEdge(new LineEdge(60, false));
        tD.getSignal(0).addEdge(new LineEdge(70, true));
        tD.getSignal(0).addEdge(new LineEdge(80, false));
        tD.getSignal(0).addEdge(new LineEdge(90, true));
        tD.getSignal(0).addEdge(new LineEdge(100, false));

        tD.getSignal(1).setName("Signal Number Two");
        tD.getSignal(1).addEdge(new LineEdge(0, false));
        tD.getSignal(1).addEdge(new LineEdge(10, true));
        tD.getSignal(1).addEdge(new LineEdge(60, false));
        tD.getSignal(1).addEdge(new LineEdge(80, true));
        tD.getSignal(1).addEdge(new LineEdge(85, false));
        tD.getSignal(1).addEdge(new LineEdge(90, true));
        tD.getSignal(1).addEdge(new LineEdge(95, false));

        tD.getSignal(2).setName("Atrocious Signal");
        tD.getSignal(2).addEdge(new LineEdge(0, false));
        tD.getSignal(2).addEdge(new LineEdge(10, true));
        tD.getSignal(2).addEdge(new LineEdge(20, false));
        tD.getSignal(2).addEdge(new LineEdge(25, true));
        tD.getSignal(2).addEdge(new LineEdge(35, false));
        tD.getSignal(2).addEdge(new LineEdge(50, true));
        tD.getSignal(2).addEdge(new LineEdge(60, false));
        tD.getSignal(2).addEdge(new LineEdge(80, true));


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        jLabel1.setText("Wira's Awesome Timing Diagram Library");

        jButton1.setText("Run CrazyThread");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Shift Domain by 5");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset Domain");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        (new CrazyThread(tD, axis, canvas)).start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        axis.setDomain(axis.getDomainStart()+5, axis.getDomainEnd()+5);
        canvas.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        axis.setDomain(0, 100);
        canvas.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SampleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    class CrazyThread extends Thread {
        private TimingDiagram tD;
        private XAxis axis;
        private DiagramCanvas canvas;

        public CrazyThread(TimingDiagram tD, XAxis axis, DiagramCanvas canvas) {
            super();
            this.tD = tD;
            this.axis = axis;
            this.canvas = canvas;
        }

        @Override
        public void run() {
            try {
                for(int i = 0; i < 1000; i++) {
                    axis.setDomain(1*i, 100+1*i);
                    canvas.repaint();
                    Thread.sleep(50);
                }
            } catch(Exception e) {

            }
        }
    }
}
