/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SampleFrame.java
 *
 * Created on Oct 31, 2011, 10:33:32 PM
 */

package plptimingdiagram.draw;

import plptimingdiagram.*;
import plptimingdiagram.signals.*;

/**
 *
 * @author wira
 */
public class SampleFrame extends javax.swing.JFrame {

    private DiagramCanvas canvas;
    private TimingDiagram tD;
    private XAxis axis;
    private CrazyThread cT;

    /** Creates new form SampleFrame */
    public SampleFrame() {
        initComponents();
        tD = new TimingDiagram();
        axis = new XAxis(0, 100, 10);
        canvas = new DiagramCanvas(tD, axis);
        canvas.setSize(container.getWidth(), container.getHeight());
        container.add(canvas);
        container.revalidate();

        tD.addSignal(new Line());
        tD.addSignal(new Line());
        tD.addSignal(new Bus());
        tD.addSignal(new Line());

        tD.getSignal(0).setName("Signal Number One");
        tD.getSignal(0).addEdge(new LineEdge(50, false));
        tD.getSignal(0).addEdge(new LineEdge(60, true));
        tD.getSignal(0).addEdge(new LineEdge(70, false));
        tD.getSignal(0).addEdge(new LineEdge(80, true));
        tD.getSignal(0).addEdge(new LineEdge(90, false));
        tD.getSignal(0).addEdge(new LineEdge(100, true));
        tD.getSignal(0).addEdge(new LineEdge(110, false));
        tD.getSignal(0).addEdge(new LineEdge(111, true));
        tD.getSignal(0).addEdge(new LineEdge(112, false));
        tD.getSignal(0).addEdge(new LineEdge(113, true));
        tD.getSignal(0).addEdge(new LineEdge(114, false));
        tD.getSignal(0).addEdge(new LineEdge(115, true));
        tD.getSignal(0).addEdge(new LineEdge(116, false));
        tD.getSignal(0).addEdge(new LineEdge(117, true));
        tD.getSignal(0).addEdge(new LineEdge(118, false));
        tD.getSignal(0).addEdge(new LineEdge(130, false));
        tD.getSignal(0).addEdge(new LineEdge(140, true));
        tD.getSignal(0).addEdge(new LineEdge(150, false));

        tD.getSignal(1).setName("Signal Number Two");
        tD.getSignal(1).addEdge(new LineEdge(50, false));
        tD.getSignal(1).addEdge(new LineEdge(60, true));
        tD.getSignal(1).addEdge(new LineEdge(110, false));
        tD.getSignal(1).addEdge(new LineEdge(130, true));
        tD.getSignal(1).addEdge(new LineEdge(135, false));
        tD.getSignal(1).addEdge(new LineEdge(140, true));
        tD.getSignal(1).addEdge(new LineEdge(145, false));


        tD.getSignal(2).setName("Bus Signal");
        tD.getSignal(2).addEdge(new BusEdge(90, 0xeeffeeffL));
        tD.getSignal(2).addEdge(new BusEdge(120, 0xaaffeeffL));
        tD.getSignal(2).addEdge(new BusEdge(150, 0xeeffccffL));

        tD.getSignal(3).setName("Another signal down here");
        tD.getSignal(3).addEdge(new LineEdge(90, true));
        tD.getSignal(3).addEdge(new LineEdge(120, false));


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        jLabel1.setText("Wira's Awesome Timing Diagram Library");

        jButton2.setText("Shift Domain by 5");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset Domain");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Run");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(20, 20, 20)
                .addComponent(jToggleButton1)
                .addContainerGap())
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(cT != null) cT.stop = true;
        axis.setDomain(axis.getDomainStart()+5, axis.getDomainEnd()+5);
        canvas.repaint();
        jToggleButton1.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(cT != null) cT.stop = true;
        axis.setDomain(0, 100);
        canvas.repaint();
        jToggleButton1.setSelected(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(jToggleButton1.isSelected()) {
            cT = new CrazyThread(tD, axis, canvas);
            cT.start();
        } else {
            cT.stop = true;
            cT = null;
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SampleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    class CrazyThread extends Thread {
        private TimingDiagram tD;
        private XAxis axis;
        private DiagramCanvas canvas;
        public boolean stop = false;

        public CrazyThread(TimingDiagram tD, XAxis axis, DiagramCanvas canvas) {
            super();
            this.tD = tD;
            this.axis = axis;
            this.canvas = canvas;
        }

        @Override
        public void run() {
            double i = axis.getDomainStart();
            try {
                while(!stop) {
                    axis.setDomain(1*i, 100+1*i);
                    canvas.repaint();
                    Thread.sleep(50);
                    i+=1;
                }
            } catch(Exception e) {

            }
        }
    }
}
