/*
    Copyright 2012 PLP Contributors

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

package plptool.extras.classroom;

import java.net.InetAddress;
import java.net.UnknownHostException;
import plptool.PLPToolbox;

/**
 *
 * @author Wira
 */
public class MyIP extends javax.swing.JFrame {

    /** Creates new form MyIP */
    public MyIP() {
        initComponents();
        getAddress();
        this.setLocationRelativeTo(null);
    }

    private void getAddress() {
        InetAddress addr;

        try {
            addr = InetAddress.getLocalHost();
            myIP.setText(addr.getHostAddress());
        } catch(UnknownHostException e) {
            myIP.setText("Failed!");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myIP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        myIP.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        myIP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myIP.setText("jLabel1");
        myIP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        myIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myIPMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myIP, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myIP, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myIPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myIPMousePressed
        this.setVisible(false);
    }//GEN-LAST:event_myIPMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel myIP;
    // End of variables declaration//GEN-END:variables

}
