/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PLPOptions.java
 *
 * Created on Dec 7, 2010, 11:38:40 PM
 */

package plptool.gui;

import plptool.Config;

/**
 *
 * @author wira
 */
public class OptionsFrame extends javax.swing.JFrame {

    private ProjectDriver plp = null;

    /** Creates new form PLPOptions */
    public OptionsFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public OptionsFrame(ProjectDriver plp) {
        this.plp = plp;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        sSimSpeed = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        simNoExecute = new javax.swing.JCheckBox();
        simBusReadDefaultZero = new javax.swing.JCheckBox();
        simDumpTraceOnFailedEval = new javax.swing.JCheckBox();
        btnApply = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(OptionsFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        sSimSpeed.setMajorTickSpacing(100);
        sSimSpeed.setMaximum(1000);
        sSimSpeed.setMinorTickSpacing(50);
        sSimSpeed.setPaintLabels(true);
        sSimSpeed.setPaintTicks(true);
        sSimSpeed.setValue(100);
        sSimSpeed.setName("sSimSpeed"); // NOI18N
        sSimSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sSimSpeedStateChanged(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        simNoExecute.setSelected(true);
        simNoExecute.setText(resourceMap.getString("simNoExecute.text")); // NOI18N
        simNoExecute.setName("simNoExecute"); // NOI18N
        simNoExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simNoExecuteActionPerformed(evt);
            }
        });

        simBusReadDefaultZero.setSelected(true);
        simBusReadDefaultZero.setText(resourceMap.getString("simBusReadDefaultZero.text")); // NOI18N
        simBusReadDefaultZero.setName("simBusReadDefaultZero"); // NOI18N
        simBusReadDefaultZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simBusReadDefaultZeroActionPerformed(evt);
            }
        });

        simDumpTraceOnFailedEval.setText(resourceMap.getString("simDumpTraceOnFailedEval.text")); // NOI18N
        simDumpTraceOnFailedEval.setName("simDumpTraceOnFailedEval"); // NOI18N
        simDumpTraceOnFailedEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simDumpTraceOnFailedEvalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simDumpTraceOnFailedEval)
                    .addComponent(simNoExecute)
                    .addComponent(sSimSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(simBusReadDefaultZero))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sSimSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simNoExecute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simBusReadDefaultZero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simDumpTraceOnFailedEval)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        btnApply.setText(resourceMap.getString("btnApply.text")); // NOI18N
        btnApply.setName("btnApply"); // NOI18N

        btnClose.setText(resourceMap.getString("btnClose.text")); // NOI18N
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApply)
                    .addComponent(btnClose))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sSimSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sSimSpeedStateChanged
        Config.simRunnerDelay = sSimSpeed.getValue();
    }//GEN-LAST:event_sSimSpeedStateChanged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void simNoExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simNoExecuteActionPerformed
        Config.simAllowExecutionOfArbitraryMem = simNoExecute.isSelected();
    }//GEN-LAST:event_simNoExecuteActionPerformed

    private void simBusReadDefaultZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simBusReadDefaultZeroActionPerformed
        Config.simBusReturnsZeroForUninitRegs = simBusReadDefaultZero.isSelected();
    }//GEN-LAST:event_simBusReadDefaultZeroActionPerformed

    private void simDumpTraceOnFailedEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simDumpTraceOnFailedEvalActionPerformed
        Config.simDumpTraceOnFailedEvaluation = simDumpTraceOnFailedEval.isSelected();
    }//GEN-LAST:event_simDumpTraceOnFailedEvalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSlider sSimSpeed;
    private javax.swing.JCheckBox simBusReadDefaultZero;
    private javax.swing.JCheckBox simDumpTraceOnFailedEval;
    private javax.swing.JCheckBox simNoExecute;
    // End of variables declaration//GEN-END:variables

}
