/*
    Copyright 2012 PLP Contributors

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

package lecturepublisher;

import com.fluendo.player.Cortado;

/**
 *
 * @author wira
 */
public class CortadoFrame extends javax.swing.JFrame {
    private Cortado applet;

    /** Creates new form CortadoFrame */
    public CortadoFrame() {
        initComponents();
        setSize(320, 240);
    }

    public void play(String url) {
        if(applet != null)
            remove(applet);
        applet = new Cortado();
        applet.setSize(this.getWidth(), this.getHeight());
        applet.setParam ("url", url);
        applet.setParam ("local", "false");
        //applet.setParam ("seekable", "true");
        //applet.setParam ("duration", "00352");
        applet.setParam ("framerate", "60");
        applet.setParam ("keepaspect", "true");
        applet.setParam ("video", "true");
        applet.setParam ("audio", "true");
        applet.setParam ("kateIndex", "0");
        //applet.setParam ("kateLanguage", "en");
        //applet.setParam ("kateCategory", "SUB");
        //applet.setParam ("audio", "false");
        applet.setParam ("bufferSize", "200");
        //applet.setParam ("userId", "wim");
        //applet.setParam ("password", "taymans");

        add(applet);
        applet.init();
        applet.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
