
# could add to CFLAGS to turn on warnings if you are using gcc
WARNS=-Wall

# change path if not running test from installed directory location
INCS=-I../../pli_incs
# maybe want -O<something> and/or -g, if you use -O use -m486
CFLAGS= -fPIC -Wall $(INCS) -dynamic -fno-common 
LFLAGS= -flat_namespace -bundle -undefined suppress

# change to your compiler
# CC=gcc

acc_probe.o:	acc_probe.c 
	$(CC) $(CFLAGS) -c acc_probe.c

acc_nxtchld.o:	acc_nxtchld.c 
	$(CC) $(CFLAGS) -c acc_nxtchld.c

accxl_drvld.o:	accxl_drvld.c 
	$(CC) $(CFLAGS) -c accxl_drvld.c

acc_prtchg.o:	acc_prtchg.c 
	$(CC) $(CFLAGS) -c acc_prtchg.c

# make rules for dynamic libraries
acc_probe.dylib:	acc_probe.o
# notice for MAC OSX you must link with cc not ld
	$(CC) $(LFLAGS) acc_probe.o -o acc_probe.dylib

acc_nxtchld.dylib:	acc_nxtchld.o
	$(CC) $(LFLAGS) acc_nxtchld.o -o acc_nxtchld.dylib

accxl_drvld.dylib:	accxl_drvld.o
	$(CC) $(LFLAGS) accxl_drvld.o -o accxl_drvld.dylib

acc_prtchg.dylib:	acc_prtchg.o
	$(CC) $(LFLAGS) acc_prtchg.o -o acc_prtchg.dylib
