/*
    Copyright 2010 David Fritz, Brian Gordon, Wira Mulia

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

package plptool.web;

import plptool.*;
import plptool.mips.*;
import plptool.mods.*;
import plptool.gui.ProjectDriver;

/**
 * Java applet interface for the PLP MIPS simulation.
 *
 * @author wira
 */
public class PLPMIPSWebSim extends javax.swing.JApplet {

    String oldStr;
    ProjectDriver plp;

    /** Initializes the applet PLPMIPSWebSim */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    btnStep.setEnabled(false);
                    btnExec.setEnabled(false);
                    txtCLI.setEnabled(false);
                    lblStatus.setText("Assemble whenever you're ready!");
                    txtEditor.setText(".org 0x10000000\n" +
                                      "\n" +
                                      "\tmove $t0, $0" +
                                      "\nloop:" +
                                      "\n\tj loop" +
                                      "\n\taddiu $t0, $t0, 1\t\t# increment $t0 by one");
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssemble = new javax.swing.JButton();
        btnStep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEditor = new javax.swing.JTextPane();
        lblStatus = new javax.swing.JLabel();
        txtCLI = new javax.swing.JTextField();
        btnExec = new javax.swing.JButton();

        setName("Form"); // NOI18N

        btnAssemble.setText("Assemble");
        btnAssemble.setName("btnAssemble"); // NOI18N
        btnAssemble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssembleActionPerformed(evt);
            }
        });

        btnStep.setText("Step!");
        btnStep.setName("btnStep"); // NOI18N
        btnStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStepActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtEditor.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtEditor.setName("txtEditor"); // NOI18N
        jScrollPane1.setViewportView(txtEditor);

        lblStatus.setText("jLabel1");
        lblStatus.setName("lblStatus"); // NOI18N

        txtCLI.setName("txtCLI"); // NOI18N
        txtCLI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCLIKeyPressed(evt);
            }
        });

        btnExec.setText("Execute");
        btnExec.setName("btnExec"); // NOI18N
        btnExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAssemble)
                        .addGap(10, 10, 10)
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                        .addComponent(btnStep))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtCLI, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btnExec)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCLI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStep)
                    .addComponent(lblStatus)
                    .addComponent(btnAssemble))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssembleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssembleActionPerformed
        if(btnAssemble.getText().equals("Back to Editor")) {
            txtEditor.setEditable(true);
            txtEditor.setText(oldStr);
            btnAssemble.setText("Assemble");
            btnStep.setEnabled(false);
            lblStatus.setText("Assemble whenever you're ready!");
            txtCLI.setEnabled(false);
            btnExec.setEnabled(false);
            return;
        }

        oldStr = txtEditor.getText();
        txtEditor.setText("");
        Msg.output = txtEditor;
        Msg.M("PLPTool build: " + Version.stamp + "\n");
        plp = new ProjectDriver(Constants.PLP_GUI_APPLET, "plpmips");
        plp.asms.add(new PLPAsmSource(oldStr, "WebApplet", 0));
        plp.assemble();

        if(plp.asm != null) {
            btnAssemble.setText("Back to Editor");
            txtEditor.setEditable(false);
            
            if (plp.simulate() != Constants.PLP_OK) {
                lblStatus.setText("Assemble failed, check your code!");
                return;
            }
            
            txtCLI.setEnabled(true);
            btnExec.setEnabled(true);
            btnStep.setEnabled(true);
            lblStatus.setText("Hit step to advance the program");
        } else {
            btnAssemble.setText("Back to Editor");
            lblStatus.setText("Assemble failed, check your code!");
            txtEditor.setEditable(false);
        }
    }//GEN-LAST:event_btnAssembleActionPerformed

    private void btnStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStepActionPerformed
        txtEditor.setText("");
        plp.sim.step();
        SimCore sc = (SimCore) plp.sim;
        
        Msg.M("Register File Contents");
        Msg.M("======================");

        for(int i = 0; i < 8; i++) {
            for(int j = 0; j < 4; j++)
                Msg.m((i+8*j) + ((i+8*j < 10) ? "  " : " ") + String.format("%08x", sc.regfile.read(i+8*j)) + "  ");

            Msg.M("");
        }
        
        Msg.M("");
        Msg.M("Instructions in-flight");
        Msg.M("======================");

        sc.wb_stage.printinstr();
        sc.mem_stage.printinstr();
        sc.ex_stage.printinstr();
        sc.id_stage.printinstr();
        sc.printfrontend();
    }//GEN-LAST:event_btnStepActionPerformed

    private void btnExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecActionPerformed
        txtEditor.setText("");
        SimCLI.simCLCommand(txtCLI.getText(), plp);
        txtCLI.setText("");
    }//GEN-LAST:event_btnExecActionPerformed

    private void txtCLIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCLIKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            btnExecActionPerformed(null);
    }//GEN-LAST:event_txtCLIKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssemble;
    private javax.swing.JButton btnExec;
    private javax.swing.JButton btnStep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtCLI;
    private javax.swing.JTextPane txtEditor;
    // End of variables declaration//GEN-END:variables

}
