/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DefaultCacheFrame.java
 *
 * Created on Jan 31, 2013, 1:04:36 PM
 */

package plptool.extras.cachesim;

/**
 *
 * @author Wira
 */
public class DefaultCacheFrame extends javax.swing.JFrame {

    /** Creates new form DefaultCacheFrame */
    public DefaultCacheFrame() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        paneConfigure = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbWordSize = new javax.swing.JComboBox();
        cmbLineSize = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbNumberOfLines = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbAssociativity = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        canvasCacheSetup = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        paneVisualize = new javax.swing.JPanel();
        paneStatistics = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(DefaultCacheFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        btnClose.setText(resourceMap.getString("btnClose.text")); // NOI18N
        btnClose.setName("btnClose"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        paneConfigure.setName("paneConfigure"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        cmbWordSize.setEditable(true);
        cmbWordSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "1", "8" }));
        cmbWordSize.setName("cmbWordSize"); // NOI18N

        cmbLineSize.setEditable(true);
        cmbLineSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "1", "8", "16", "32", "64", "128", "256", "512" }));
        cmbLineSize.setName("cmbLineSize"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        cmbNumberOfLines.setEditable(true);
        cmbNumberOfLines.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "4", "8", "16", "32", "64", "128", "256", "1024", "4196", "16384" }));
        cmbNumberOfLines.setName("cmbNumberOfLines"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        cmbAssociativity.setEditable(true);
        cmbAssociativity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "8", "16", "32", "64", "128", "256", "512" }));
        cmbAssociativity.setName("cmbAssociativity"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        canvasCacheSetup.setBackground(resourceMap.getColor("canvasCacheSetup.background")); // NOI18N
        canvasCacheSetup.setName("canvasCacheSetup"); // NOI18N

        javax.swing.GroupLayout canvasCacheSetupLayout = new javax.swing.GroupLayout(canvasCacheSetup);
        canvasCacheSetup.setLayout(canvasCacheSetupLayout);
        canvasCacheSetupLayout.setHorizontalGroup(
            canvasCacheSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        canvasCacheSetupLayout.setVerticalGroup(
            canvasCacheSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout paneConfigureLayout = new javax.swing.GroupLayout(paneConfigure);
        paneConfigure.setLayout(paneConfigureLayout);
        paneConfigureLayout.setHorizontalGroup(
            paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneConfigureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(canvasCacheSetup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneConfigureLayout.createSequentialGroup()
                        .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbNumberOfLines, javax.swing.GroupLayout.Alignment.LEADING, 0, 666, Short.MAX_VALUE)
                            .addComponent(cmbLineSize, javax.swing.GroupLayout.Alignment.LEADING, 0, 666, Short.MAX_VALUE)
                            .addComponent(cmbWordSize, javax.swing.GroupLayout.Alignment.LEADING, 0, 666, Short.MAX_VALUE)
                            .addComponent(cmbAssociativity, 0, 666, Short.MAX_VALUE))))
                .addContainerGap())
        );
        paneConfigureLayout.setVerticalGroup(
            paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneConfigureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbWordSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLineSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNumberOfLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAssociativity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(canvasCacheSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("paneConfigure.TabConstraints.tabTitle"), paneConfigure); // NOI18N

        paneVisualize.setName("paneVisualize"); // NOI18N

        javax.swing.GroupLayout paneVisualizeLayout = new javax.swing.GroupLayout(paneVisualize);
        paneVisualize.setLayout(paneVisualizeLayout);
        paneVisualizeLayout.setHorizontalGroup(
            paneVisualizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        paneVisualizeLayout.setVerticalGroup(
            paneVisualizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(resourceMap.getString("paneVisualize.TabConstraints.tabTitle"), paneVisualize); // NOI18N

        paneStatistics.setName("paneStatistics"); // NOI18N

        javax.swing.GroupLayout paneStatisticsLayout = new javax.swing.GroupLayout(paneStatistics);
        paneStatistics.setLayout(paneStatisticsLayout);
        paneStatisticsLayout.setHorizontalGroup(
            paneStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        paneStatisticsLayout.setVerticalGroup(
            paneStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(resourceMap.getString("paneStatistics.TabConstraints.tabTitle"), paneStatistics); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefaultCacheFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel canvasCacheSetup;
    private javax.swing.JComboBox cmbAssociativity;
    private javax.swing.JComboBox cmbLineSize;
    private javax.swing.JComboBox cmbNumberOfLines;
    private javax.swing.JComboBox cmbWordSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel paneConfigure;
    private javax.swing.JPanel paneStatistics;
    private javax.swing.JPanel paneVisualize;
    // End of variables declaration//GEN-END:variables

}
