/*
    Copyright 2013 Wira Mulia

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package plptool.extras.cachesim;

import plptool.PLPToolbox;

/**
 *
 * @author wira
 */
public class DefaultCacheFrame extends javax.swing.JFrame {

    DefaultCache e;
    CacheVisualizerCanvas c;
    CacheStatisticsCanvas s;
    
    /** Creates new form DefaultCacheFrame */
    public DefaultCacheFrame() {
        initComponents();
        c = new CacheVisualizerCanvas(this);
        s = new CacheStatisticsCanvas(this);
        paneVisualizeContainer.add(c);
        paneStatisticsContainer.add(s);
        c.setSize(paneVisualizeContainer.getSize());
        s.setSize(paneStatisticsContainer.getSize());
        paneVisualizeContainer.revalidate();
        paneStatisticsContainer.revalidate();
        update();
    }
    
    private void removeCacheFromLog() {
        Log.destroyCacheFrame(this);       
    }
    
    public final void update() {
        if(e != null && e.lastAccess != -1) {
            c.highlightSet((int) (e.lastAccess >> e.blockOffset) % (e.blocks / e.associativity));
        }
        if(e != null && e.lastAccess == -1)
            c.highlightSet(-1);
        c.repaint();
        s.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        paneConfigure = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbWordOffset = new javax.swing.JComboBox();
        cmbNumberOfLines = new javax.swing.JComboBox();
        cmbAssociativity = new javax.swing.JComboBox();
        btnCreate = new javax.swing.JButton();
        chkInstructions = new javax.swing.JCheckBox();
        chkWrites = new javax.swing.JCheckBox();
        chkWriteAllocate = new javax.swing.JCheckBox();
        chkWriteThrough = new javax.swing.JCheckBox();
        chkData = new javax.swing.JCheckBox();
        paneVisualize = new javax.swing.JPanel();
        paneVisualizeContainer = new javax.swing.JPanel();
        paneStatistics = new javax.swing.JPanel();
        paneStatisticsContainer = new javax.swing.JPanel();
        paneExtras = new javax.swing.JPanel();
        btnDumpContents = new javax.swing.JButton();
        btnDumpStatistics = new javax.swing.JButton();
        btnResetCache = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CacheSim");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        paneConfigure.setName("paneConfigure"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel1.setText("Block size (bytes) :");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel2.setText("Number of blocks :");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel4.setText("Associativity :");
        jLabel4.setName("jLabel4"); // NOI18N

        cmbWordOffset.setEditable(true);
        cmbWordOffset.setFont(new java.awt.Font("Dialog", 1, 24));
        cmbWordOffset.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "8", "16", "32", "64", "128", "256" }));
        cmbWordOffset.setName("cmbWordOffset"); // NOI18N

        cmbNumberOfLines.setEditable(true);
        cmbNumberOfLines.setFont(new java.awt.Font("Dialog", 1, 24));
        cmbNumberOfLines.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "16", "32", "64", "128", "256", "512", "1024", "4096", "8192", "16384", "32768" }));
        cmbNumberOfLines.setName("cmbNumberOfLines"); // NOI18N

        cmbAssociativity.setEditable(true);
        cmbAssociativity.setFont(new java.awt.Font("Dialog", 1, 24));
        cmbAssociativity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "8", "16", "32" }));
        cmbAssociativity.setName("cmbAssociativity"); // NOI18N

        btnCreate.setFont(new java.awt.Font("Dialog", 1, 24));
        btnCreate.setText("Create Cache");
        btnCreate.setName("btnCreate"); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        chkInstructions.setFont(new java.awt.Font("Tahoma", 1, 24));
        chkInstructions.setText("Cache Instructions");
        chkInstructions.setName("chkInstructions"); // NOI18N

        chkWrites.setFont(new java.awt.Font("Tahoma", 1, 24));
        chkWrites.setText("Cache Writes");
        chkWrites.setName("chkWrites"); // NOI18N

        chkWriteAllocate.setFont(new java.awt.Font("Tahoma", 1, 24));
        chkWriteAllocate.setText("Write-allocate");
        chkWriteAllocate.setName("chkWriteAllocate"); // NOI18N

        chkWriteThrough.setFont(new java.awt.Font("Tahoma", 1, 24));
        chkWriteThrough.setText("Write-through");
        chkWriteThrough.setName("chkWriteThrough"); // NOI18N

        chkData.setFont(new java.awt.Font("Tahoma", 1, 24));
        chkData.setText("Cache Data");
        chkData.setName("chkData"); // NOI18N

        javax.swing.GroupLayout paneConfigureLayout = new javax.swing.GroupLayout(paneConfigure);
        paneConfigure.setLayout(paneConfigureLayout);
        paneConfigureLayout.setHorizontalGroup(
            paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneConfigureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkWriteThrough)
                    .addComponent(chkWriteAllocate)
                    .addComponent(chkInstructions)
                    .addGroup(paneConfigureLayout.createSequentialGroup()
                        .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAssociativity, javax.swing.GroupLayout.Alignment.TRAILING, 0, 494, Short.MAX_VALUE)
                            .addComponent(cmbWordOffset, javax.swing.GroupLayout.Alignment.TRAILING, 0, 494, Short.MAX_VALUE)
                            .addComponent(cmbNumberOfLines, 0, 494, Short.MAX_VALUE)))
                    .addComponent(chkData)
                    .addComponent(chkWrites)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneConfigureLayout.setVerticalGroup(
            paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneConfigureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbWordOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNumberOfLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(paneConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAssociativity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(chkData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkInstructions)
                .addGap(18, 18, 18)
                .addComponent(chkWrites)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkWriteAllocate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkWriteThrough)
                .addGap(18, 18, 18)
                .addComponent(btnCreate)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configure", paneConfigure);

        paneVisualize.setName("paneVisualize"); // NOI18N

        paneVisualizeContainer.setBackground(new java.awt.Color(0, 0, 0));
        paneVisualizeContainer.setName("paneVisualizeContainer"); // NOI18N

        javax.swing.GroupLayout paneVisualizeContainerLayout = new javax.swing.GroupLayout(paneVisualizeContainer);
        paneVisualizeContainer.setLayout(paneVisualizeContainerLayout);
        paneVisualizeContainerLayout.setHorizontalGroup(
            paneVisualizeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        paneVisualizeContainerLayout.setVerticalGroup(
            paneVisualizeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneVisualizeLayout = new javax.swing.GroupLayout(paneVisualize);
        paneVisualize.setLayout(paneVisualizeLayout);
        paneVisualizeLayout.setHorizontalGroup(
            paneVisualizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneVisualizeContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneVisualizeLayout.setVerticalGroup(
            paneVisualizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneVisualizeContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualize", paneVisualize);

        paneStatistics.setName("paneStatistics"); // NOI18N

        paneStatisticsContainer.setBackground(new java.awt.Color(0, 0, 0));
        paneStatisticsContainer.setName("paneStatisticsContainer"); // NOI18N

        javax.swing.GroupLayout paneStatisticsContainerLayout = new javax.swing.GroupLayout(paneStatisticsContainer);
        paneStatisticsContainer.setLayout(paneStatisticsContainerLayout);
        paneStatisticsContainerLayout.setHorizontalGroup(
            paneStatisticsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        paneStatisticsContainerLayout.setVerticalGroup(
            paneStatisticsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneStatisticsLayout = new javax.swing.GroupLayout(paneStatistics);
        paneStatistics.setLayout(paneStatisticsLayout);
        paneStatisticsLayout.setHorizontalGroup(
            paneStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneStatisticsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneStatisticsLayout.setVerticalGroup(
            paneStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneStatisticsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Statistics", paneStatistics);

        paneExtras.setName("paneExtras"); // NOI18N

        btnDumpContents.setText("Dump Contents");
        btnDumpContents.setName("btnDumpContents"); // NOI18N
        btnDumpContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDumpContentsActionPerformed(evt);
            }
        });

        btnDumpStatistics.setText("Dump Statistics");
        btnDumpStatistics.setName("btnDumpStatistics"); // NOI18N
        btnDumpStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDumpStatisticsActionPerformed(evt);
            }
        });

        btnResetCache.setText("Reset Cache");
        btnResetCache.setName("btnResetCache"); // NOI18N
        btnResetCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCacheActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtOutput.setColumns(20);
        txtOutput.setEditable(false);
        txtOutput.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtOutput.setRows(5);
        txtOutput.setName("txtOutput"); // NOI18N
        jScrollPane1.setViewportView(txtOutput);

        javax.swing.GroupLayout paneExtrasLayout = new javax.swing.GroupLayout(paneExtras);
        paneExtras.setLayout(paneExtrasLayout);
        paneExtrasLayout.setHorizontalGroup(
            paneExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                    .addGroup(paneExtrasLayout.createSequentialGroup()
                        .addComponent(btnDumpContents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDumpStatistics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                        .addComponent(btnResetCache)))
                .addContainerGap())
        );
        paneExtrasLayout.setVerticalGroup(
            paneExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDumpContents)
                    .addComponent(btnDumpStatistics)
                    .addComponent(btnResetCache))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Extras", paneExtras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    removeCacheFromLog();
}//GEN-LAST:event_btnCloseActionPerformed

private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    try {
        int blockSize = Integer.parseInt((String) cmbWordOffset.getSelectedItem());
        int numberOfLines = Integer.parseInt((String) cmbNumberOfLines.getSelectedItem());
        int associativity = Integer.parseInt((String) cmbAssociativity.getSelectedItem());
        int cacheSize, indexBits;
        int blockOffset = (int) (Math.log(blockSize) / Math.log(2));

        if(!chkInstructions.isSelected() && !chkData.isSelected()) {
            PLPToolbox.showErrorDialog(this, "We need to cache SOMETHING! (check either instruction, data, or both)");
            return;
        }

        if(numberOfLines < associativity) {
            PLPToolbox.showErrorDialog(this, "Associativity can not be greater than the number of blocks.");
            return;
        }
        
        if(blockSize <= 0 | numberOfLines <= 0 | associativity <= 0 |
                (blockSize & (blockSize - 1)) != 0 |
                (numberOfLines & (numberOfLines - 1)) != 0 |
                (associativity & (associativity - 1)) != 0) {
            PLPToolbox.showErrorDialog(this, "Cache parameters must be powers of two.");
            return;
        }
        
        if(chkWrites.isSelected() && !chkWriteThrough.isSelected() && !chkWriteAllocate.isSelected()) {
            PLPToolbox.showErrorDialog(this, "Write-back (no write-through) requires write-allocate.");
            return;
        }      
        
        e = new DefaultCache(null);
        e.setProperties(blockOffset, associativity, numberOfLines,
                chkInstructions.isSelected(), chkData.isSelected(),
                chkWrites.isSelected(), chkWriteThrough.isSelected(), chkWriteAllocate.isSelected());
        e.reset();
        Log.head.add(e);
        
        cacheSize = numberOfLines * 8 * blockSize;
        indexBits = (int) (Math.log(numberOfLines / associativity) / Math.log(2));
        plptool.Msg.M("CacheSim: word parameters: " + blockOffset + " bits of offset, " +
                indexBits + " bits of index");
        plptool.Msg.M("CacheSim: Cacheable data size is " + cacheSize + " bytes");
        
    } catch(NumberFormatException e) {
        PLPToolbox.showErrorDialog(this, "Failed to parse cache parameters.");
    }
}//GEN-LAST:event_btnCreateActionPerformed

private void btnDumpContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDumpContentsActionPerformed
    if(e != null)
        txtOutput.setText(e.dumpContents());
}//GEN-LAST:event_btnDumpContentsActionPerformed

private void btnDumpStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDumpStatisticsActionPerformed
    if(e != null)
        txtOutput.setText(e.stats.print());
}//GEN-LAST:event_btnDumpStatisticsActionPerformed

private void btnResetCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCacheActionPerformed
    if(e != null)
        e.logReset();
}//GEN-LAST:event_btnResetCacheActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    removeCacheFromLog();
}//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDumpContents;
    private javax.swing.JButton btnDumpStatistics;
    private javax.swing.JButton btnResetCache;
    private javax.swing.JCheckBox chkData;
    private javax.swing.JCheckBox chkInstructions;
    private javax.swing.JCheckBox chkWriteAllocate;
    private javax.swing.JCheckBox chkWriteThrough;
    private javax.swing.JCheckBox chkWrites;
    private javax.swing.JComboBox cmbAssociativity;
    private javax.swing.JComboBox cmbNumberOfLines;
    private javax.swing.JComboBox cmbWordOffset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel paneConfigure;
    private javax.swing.JPanel paneExtras;
    private javax.swing.JPanel paneStatistics;
    private javax.swing.JPanel paneStatisticsContainer;
    private javax.swing.JPanel paneVisualize;
    private javax.swing.JPanel paneVisualizeContainer;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
