/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetupDOT.java
 *
 * Created on Apr 30, 2012, 6:44:08 PM
 */

package plptool.extras.flowchart;

import plptool.*;
import plptool.gui.PLPToolApp;

/**
 *
 * @author Wira
 */
public class SetupDOT extends javax.swing.JDialog {
    private PLPToolConnector connector;
    private fileFinder fileFinderThread;
    private titleUpdater titleUpdaterThread;
    private ThreadSync threadSync;

    /** Creates new form SetupDOT */
    public SetupDOT(java.awt.Frame parent, PLPToolConnector connector) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.connector = connector;
        this.fileFinderThread = null;
        this.titleUpdaterThread = null;
        threadSync = new ThreadSync();
        init();
    }

    private void init() {
        PLPToolbox.attachHideOnEscapeListener(this);
        txtPath.setText(connector.getDotPath());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnApply = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setup GraphViz / DOT");
        setResizable(false);

        jLabel1.setText("PLPTool flowchart tool requires GraphViz to generate flowchart images");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setText("Enter \"dot\" program location (\"dot.exe\" for Windows, \"dot\" for other platforms):");

        btnBrowse.setText("Browse...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnApply.setText("Apply");
        btnApply.setPreferredSize(new java.awt.Dimension(81, 23));
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(80, 23));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnFind.setText("Try to find it for me");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFind)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPath, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnApply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBrowse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        java.io.File f = PLPToolbox.openFileDialog(Constants.launchPath);
        if(f != null)
            txtPath.setText(f.getAbsolutePath());
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        String dotPath = PLPToolApp.getAttributes().get("flowchart_dotpath");
        if(dotPath != null) {
            connector.setDotPath(dotPath);
            txtPath.setText(dotPath);
        }
        if(fileFinderThread != null) {
            threadSync.stop();
            fileFinderThread = null;
            titleUpdaterThread = null;
            btnFind.setText("Try to find it for me");
            btnApply.setEnabled(true);
            btnBrowse.setEnabled(true);
            txtPath.setEnabled(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        String path = txtPath.getText();
        java.io.File f = new java.io.File(path);
        if(f.exists() && !f.isDirectory()) {
            PLPToolApp.getAttributes().put("flowchart_dotpath", path);
            connector.setDotPath(path);
            this.dispose();
        } else
            Msg.E(path + " does not exist", Constants.PLP_GENERAL_IO_ERROR,
                    null);
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        if(fileFinderThread == null) {
            btnFind.setText("Cancel find");
            btnApply.setEnabled(false);
            btnBrowse.setEnabled(false);
            txtPath.setEnabled(false);
            threadSync.start();
            fileFinderThread = new fileFinder();
            fileFinderThread.start();
            titleUpdaterThread = new titleUpdater(this);
            titleUpdaterThread.start();

        } else {
            threadSync.stop();
            fileFinderThread = null;
            titleUpdaterThread = null;
            btnFind.setText("Try to find it for me");
            btnApply.setEnabled(true);
            btnBrowse.setEnabled(true);
            txtPath.setEnabled(true);
            setTitle("Setup GraphViz / DOT");
        }
    }//GEN-LAST:event_btnFindActionPerformed

    class fileFinder extends Thread {

        @Override
        public void run() {
            String f = null;

            if(PLPToolbox.isHostLinux()) {
                f = PLPToolbox.findFileInDirectory("/usr", "dot", true, threadSync);
                if(f == null) {
                    PLPToolbox.findFileInDirectory("/", "dot", true, threadSync);
                }
            } else if(PLPToolbox.getOS(false) == Constants.PLP_OS_WIN_32 ||
                      PLPToolbox.getOS(false) == Constants.PLP_OS_WIN_64) {
                f = PLPToolbox.findFileInDirectory("C:\\Program Files (x86)", "dot.exe", true, threadSync);
                f = (f == null ? PLPToolbox.findFileInDirectory("C:\\Program Files", "dot.exe", true, threadSync) : f);
                f = (f == null ? PLPToolbox.findFileInDirectory("C:\\", "dot.exe", true, threadSync) : f);
            } else {

            }

            if(f != null)
                txtPath.setText(f);

            fileFinderThread = null;
            btnFind.setText("Try to find it for me");
            btnApply.setEnabled(true);
            btnBrowse.setEnabled(true);
            txtPath.setEnabled(true);
            setTitle("Setup GraphViz / DOT");
            threadSync.stop();
        }
    }

    class titleUpdater extends Thread {
        private Boolean cancel;
        private SetupDOT f;

        public titleUpdater(SetupDOT f) {
            this.f = f;
        }

        @Override
        public void run() {
            while(!threadSync.isStopped()) {
                f.setTitle("Searching in " + threadSync.getString() + "...");
                try {
                    Thread.sleep(50);
                } catch(Exception e) {
                    Msg.trace(e);
                }
            }
            f.setTitle("Setup GraphViz / DOT");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables

}
