/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UARTFrame.java
 *
 * Created on Feb 5, 2011, 5:57:54 PM
 */

package plptool.mods;

/**
 *
 * @author fritz
 */
public class UARTFrame extends javax.swing.JInternalFrame {
    UART u;
    
    /** Creates new form UARTFrame */
    public UARTFrame() {
        initComponents();
    }

    public void setUART(UART f) {
        u = f;
    }
    public void addText(long d) {
        txtUART.append(String.format("%c",(char)d));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtUART = new javax.swing.JTextArea();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plptool.gui.PLPToolApp.class).getContext().getResourceMap(UARTFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setBackground(resourceMap.getColor("jScrollPane1.background")); // NOI18N
        jScrollPane1.setForeground(resourceMap.getColor("jScrollPane1.foreground")); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtUART.setBackground(resourceMap.getColor("txtUART.background")); // NOI18N
        txtUART.setColumns(20);
        txtUART.setEditable(false);
        txtUART.setForeground(resourceMap.getColor("txtUART.foreground")); // NOI18N
        txtUART.setRows(5);
        txtUART.setDisabledTextColor(resourceMap.getColor("txtUART.disabledTextColor")); // NOI18N
        txtUART.setName("txtUART"); // NOI18N
        txtUART.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUARTKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtUART);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUARTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUARTKeyTyped
         u.receivedData(evt.getKeyChar());
    }//GEN-LAST:event_txtUARTKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtUART;
    // End of variables declaration//GEN-END:variables

}
