/*
    Copyright 2012 PLP Contributors

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

package plptool.extras.collab;

import plptool.*;
import java.io.*;
import java.net.*;

/**
 *
 * @author Wira
 */
public class Client extends javax.swing.JFrame {

    private Socket s;
    private ClientReceiveService cs;
    PrintWriter writer;

    /** Creates new form Client */
    public Client() {
        initComponents();
    }

    public void connect() {
        try {
            s = new Socket(txtHost.getText(), Integer.parseInt(txtPort.getText()));
            writer = new PrintWriter(s.getOutputStream(), true);
            cs = new ClientReceiveService(s, this);
            cs.start();
            setState(true, false);
        } catch(UnknownHostException uhe) {
            Msg.E("Client.connect: Unable to connect to " + txtHost.getText() + ":" +
                   txtHost.getText(), Constants.PLP_GENERAL_IO_ERROR, null);
            tglConnect.setSelected(false);
            setState(false, false);
        } catch(IOException ioe) {
            Msg.E("Client.connect: I/O error", Constants.PLP_GENERAL_IO_ERROR,
                    null);
            tglConnect.setSelected(false);
            setState(false, false);
        } catch(Exception e) {
            Msg.E("Client.connect: Unknown error", Constants.PLP_GENERIC_ERROR,
                    null);
            if(Constants.debugLevel >= 2)
                e.printStackTrace();
            tglConnect.setSelected(false);
            setState(false, false);
        }     
    }

    public void disconnect() {
        cmd("QUIT");
        tglConnect.setSelected(false);
        setState(false, false);
    }

    public void cleanup() {
        try {
            writer.close();
            s.close();
        } catch(IOException e) {
            Msg.E("Cleanup error.", Constants.PLP_GENERAL_IO_ERROR, this);
        }
    }

    public void setState(boolean c, boolean v) {
        Msg.D("Setting to " + c, 2, null);
        txtNickname.setEnabled(!c);
        btnME.setEnabled(c);
        txtHost.setEnabled(!c);
        txtPort.setEnabled(!c);
        txtCapture.setEnabled(c);
        btnSend.setEnabled(v);
    }

    public void sendText() {
        try {
            cmd("TEXT");
            String lines[] = txtCapture.getText().split("\\r?\\n");
            for(int i = 0; i < lines.length; i++)
                writer.write(lines[i] + "\n");
            writer.flush();
            cmd("ENDTEXT");
            txtCapture.setText("");
        } catch(Exception ioe) {
            Msg.E("Send data failed.", Constants.PLP_GENERAL_IO_ERROR, this);
        }
    }

    public void cmd(String cmd) {
        writer.write("%%" + cmd + "\n");
        writer.flush();
    }

    public String toString() {
        return "collab.Client";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        tglConnect = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        btnME = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCapture = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        txtPort = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setResizable(false);

        jLabel1.setText("Host server : ");

        tglConnect.setText("CONNECT");
        tglConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglConnectActionPerformed(evt);
            }
        });

        jLabel2.setText("Nickname :");

        btnME.setText("ME!");
        btnME.setEnabled(false);
        btnME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEActionPerformed(evt);
            }
        });

        jLabel3.setText("Status :");

        txtStatus.setEditable(false);
        txtStatus.setText("Not connected");

        jLabel4.setText("Keyboard capture area :");

        txtCapture.setColumns(20);
        txtCapture.setRows(5);
        txtCapture.setEnabled(false);
        jScrollPane1.setViewportView(txtCapture);

        btnClose.setText("I'm done...");

        btnSend.setText("SEND");
        btnSend.setEnabled(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtPort.setText("11000");

        jLabel5.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHost, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(txtNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglConnect))
                    .addComponent(btnME, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglConnect)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnME, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSend))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglConnectActionPerformed
        if(tglConnect.isSelected())
            connect();
        else
            disconnect();
    }//GEN-LAST:event_tglConnectActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        sendText();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEActionPerformed
        cmd("REQ");
    }//GEN-LAST:event_btnMEActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnME;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton tglConnect;
    private javax.swing.JTextArea txtCapture;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

}
