ARCHFLGS= -mcpu=v8
OPTFLGS=-fno-strength-reduce -fomit-frame-pointer
CFLAGS= $(ARCHFLGS) -pipe $(OPTFLGS) -O2 
#CFLAGS= $(ARCHFLGS) -pipe $(OPTFLGS) -g -Wall
#CFLAGS= -pg -g -Wall
#CFLAGS= -g -Wall

CC=gcc
LIBS=-lm

vcddiff:	vcddiff.o 
	$(CC) $(CFLAGS) $(OPTFLGS) vcddiff.o $(LIBS) -o vcddiff 
	rm vcddiff.o
	mv vcddiff ../../bin

vcddiff.o:	vcddiff.c vcddiff.h
	$(CC) $(CFLAGS) -c vcddiff.c
